name: branching
run-name: branching
on: push
jobs:
  etape1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - run: bash branching.sh
      - run: echo "end of file"
